# Run basic tests for Rust

name: Rust tests

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ubuntu Rust tests
    
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo build --verbose